export const QueryKeys = {
    PRODUCTS: "products",
    SIZES: "sizes",
    COLORS: "colors",
    SHOPNOWS:"shopnows",
    SWIPERS:"swipers",
    DISCOVERNOWS:"discovernows",
    INSTASWIPERS:"instaswipers",
    LIKES:"likes",
    RESULTS:"results",
    BLOGS:"blogs",
    DETAILSWIPERS:"detailswipers",
    CERTIFICATES:"certificates",
    FILTERS:"filters",
    ABOUTVALUES:"aboutvalues",
    ABOUTBOARDS:"aboutboards",
    CHOOSEUS:"chooseus",
    PROJECTCARDS:"projectcards",
    NEWSCARDS:"newscards",
    NEWSSWIP:"newsswip",
    KSMS:"ksms",
    SERVICES:"services",
    SERVICESWIPERS:"serviceswipers",
    SERVICECOMMERCESWIPERS:"servicecommerceswipers",
    SERVICESCOMMERCE:"servicescommerce",
    SERVICESLOGISTICS:"serviceslogistics",
    SERVICEOFFICES:"serviceoffices",
    SERVICESETEMS:"servicesetems",
    SERVICEDETAILSWIPER:"servicedetailswiper",
    CAREERSWIPER:"careerswiper"
  };